### ISSUE TITLE
dynamic variables priority order is incorrect

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#277] opened 2020-06-25 21:27 UTC
In my hands, if I include a dynamic variables script, then these variables are treated as a *lower* priority than elements in the divvy config package.

I think the dynamic variables should have a *higher* priority than elements in the divvy config package.

**Comment by stolarczyk** [comment] 2020-07-02 16:54
I can't reproduce this or I just don't understand the problem. What do you mean by "divvy config package"? 

When I use the dynamic variables feature, the selected values are used correctly by divvy in the submission scripts. 
By looking at the relevant lines I see that whatever is returned by `choose_resource_package` (dynamic variables are given priority there) method is only overwritten by the CLI resources specification:

https://github.com/pepkit/looper/blob/0c5f94c54b086232e538571a37111526cef94d80/looper/conductor.py#L406-L409

**Comment by nsheff** [comment] 2020-07-02 16:57
I put 'partition: largemem' in dynamic variables, they are submitted to 'standard' anyway because of this line:

https://github.com/pepkit/divcfg/blob/98ba06587d49f4cc9f630cd7d157fb81a16c95c9/uva_rivanna.yaml#L19

the dynamic variable should have precedence.

**Comment by stolarczyk** [comment] 2020-07-02 17:32
should be fixed now

**Closed** 2021-01-15 14:14 UTC
Labels: likely-solved
