### ISSUE TITLE
how to specify looper output dir

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#399] opened 2023-08-14 16:19 UTC
if you only specify `output_dir` in the looper config, you get this error:

```
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 1200, in main
    CheckerOld(prj)(flags=args.flags)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 201, in __call__
    files_by_flag = fetch_flag_files(prj=self.prj, flags=flags)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/utils.py", line 65, in fetch_flag_files
    folder = sample_folder(prj, s)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/utils.py", line 133, in sample_folder
    return os.path.join(prj.results_folder, sample[prj.sample_table_index])
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 65, in __getattr__
    return getattr(self.prj, item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 214, in results_folder
    return self._out_subdir_path(RESULTS_SUBDIR_KEY, default="results_pipeline")
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 235, in _out_subdir_path
    parent = getattr(self, OUTDIR_KEY)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 174, in output_dir
    return self._extra_cli_or_cfg(OUTDIR_KEY, strict=True)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 201, in _extra_cli_or_cfg
    raise MisconfigurationException(
looper.exceptions.MisconfigurationException: 'output_dir' is missing. Provide it in the 'looper' section of the project configuration file

```

**Comment by khoroshevskyi** [comment] 2023-08-18 08:42
I can't reproduce this error,in hello-looper it wlorks fine ...

**Comment by donaldcampbelljr** [comment] 2023-12-22 18:20
Closing for now.

**Closed by donaldcampbelljr** 2023-12-22 18:20 UTC
Labels: likely-solved
