### ISSUE TITLE
Is the path variable still a thing?

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#322] opened 2021-03-26 13:32 UTC
Here, we introduce the `path` key in the pipeline interface.

http://looper.databio.org/en/latest/writing-a-pipeline-interface/

![image](https://user-images.githubusercontent.com/5271009/112638617-d2fa2b80-8e15-11eb-9386-c210445fd6bd.png)

Are these docs outdated? I seem to recall that we switched from this to use `var_templates` 

There are very few docs related to this and I think some of these are wrong...

**Comment by aaron-gu** [comment] 2021-05-06 18:59
This is working for me in the hello looper repository as well as a project I created separately.

**Comment by donaldcampbelljr** [comment] 2023-03-31 18:39
Currently, in v1.4.0, one can replace 
`path: count_lines.sh `

with

![image](https://user-images.githubusercontent.com/125581724/229197430-c8201401-dbf9-457d-bc8e-df47aa17f734.png)

or use:
![image](https://user-images.githubusercontent.com/125581724/229197180-588d20a3-1801-4311-b6e8-d0b788313334.png)

However, one page of our [documentation](https://looper.databio.org/en/latest/pipeline-interface-specification/) instructs to use: 
![image](https://user-images.githubusercontent.com/125581724/229196453-555135bd-a95b-4511-871e-e375c272d351.png)

![image](https://user-images.githubusercontent.com/125581724/229197090-ea076d97-98e1-48a5-a39d-1e14dfd45853.png)

However, this does not execute the pipeline script as expected. Looper debug output:

`DEBU 14:11:53 | looper.utils:utils:207 > rendered arg str: {looper.piface_dir}/pipeline/count_lines.sh data/frog2_data.txt --output-parent /home/drc/hello_looper_results/results_pipeline/frog_2``

vs executing the pipeline .sh as expected:

` looper.utils:utils:207 > rendered arg str: pipeline/count_lines.sh data/frog2_data.txt`

It appears that in the 1st case, `rendered arg str: `shows `{looper.piface_dir}` is not being replaced with the correct file path to call the pipeline script.

Also, using the example from the documentation page, `namespace pipelines` also shows incorrect path, e.g. `pipeline/pipeline/count_lines.sh` vs `pipeline/count_lines.sh`

**Comment by donaldcampbelljr** [comment] 2023-04-04 15:13
Downgrading to Looper 1.3.2 and using Python 3.8:

Still not calling the script due to an 'extra' `"pipeline"` in the called path:
![image](https://user-images.githubusercontent.com/125581724/229833142-636def44-36a1-44e3-931b-bb704192340d.png)

![image](https://user-images.githubusercontent.com/125581724/229833244-77fb51cd-16cb-4bf9-9c95-e6a9fc3eb74d.png)

However, if one uses `{looper.piface_dir}/count_lines.sh` vs  `{looper.piface_dir}/pipeline/count_lines.sh`, it **will** call the script properly:
![image](https://user-images.githubusercontent.com/125581724/229833542-61db6959-b979-4c0d-9e2d-9fd544f75ace.png)

![image](https://user-images.githubusercontent.com/125581724/229833762-579a31e8-1a37-47b0-a374-4af071fd9ca1.png)

Submission for an example sample using Looper 1.3.2:
![image](https://user-images.githubusercontent.com/125581724/229836634-9332ae6f-86c9-4f3b-95e6-f863fe286450.png)

Submission for an example sample using the same config files but using Looper 1.4.0:
![image](https://user-images.githubusercontent.com/125581724/229837010-a8df0f45-5b81-471b-8bff-b548d05aca67.png)

**Comment by donaldcampbelljr** [comment] 2023-04-05 16:28
Additional information, confirmed that:
 
Command template arguments that also contain {} will not parse correctly, e.g. {pipeline.var_templates.pipeline}  ------> points to ------> '{looper.piface_dir}/count_lines.sh'

Not rendered appropriately:
![Screenshot from 2023-04-05 11-25-47](https://user-images.githubusercontent.com/125581724/230136071-78a6be4d-5beb-4866-bcef-fb2de67273f3.png)


Changing the config file to have all '{}' commands within command template will rendered the proper script path and execute the pipeline as expected:
![Screenshot from 2023-04-05 11-37-36](https://user-images.githubusercontent.com/125581724/230136186-d7f1693b-1cae-41c5-abfb-6916b5e63d3d.png)

I believe this occurs in function: `def jinja_render_template_strictly`.

**Comment by donaldcampbelljr** [comment] 2023-04-07 14:50
Added check in utils.py to look for nested commands: f3ae33f4f6ed88ff6569b52c225b05035c6d7d42 

Next Steps:

1. Update Looper Documentation to show examples using var_templates/pipeline: https://looper.databio.org/en/latest/writing-a-pipeline-interface/
2. Note that path variable will be deprecated.
3. Update hello_world repository to include var_templates (instead of simple path variable).

**Comment by donaldcampbelljr** [comment] 2023-04-12 14:35
This is now fixed with https://github.com/pepkit/looper/commit/79fef3e68926942d452753adddad07ece962b525

**Closed by donaldcampbelljr** 2023-04-12 14:35 UTC
Labels: good first issue, docs
